-- REALISTIC POKER BOT NAMES
-- Replaces generic botxxx with immersive nicknames

DELETE FROM public.bots WHERE name LIKE 'bot%';

INSERT INTO public.bots (id, name, personality) VALUES
(gen_random_uuid(), 'TexasDolly', 'aggressive'),
(gen_random_uuid(), 'RiverRat', 'standard'),
(gen_random_uuid(), 'AcesHigh', 'aggressive'),
(gen_random_uuid(), 'TurboTom', 'standard'),
(gen_random_uuid(), 'BluffMaster', 'aggressive'),
(gen_random_uuid(), 'PokerShark', 'standard'),
(gen_random_uuid(), 'TiltProof', 'standard'),
(gen_random_uuid(), 'SlowPlaySam', 'passive'),
(gen_random_uuid(), 'AllInAnnie', 'aggressive'),
(gen_random_uuid(), 'MuckItAll', 'passive'),
(gen_random_uuid(), 'GrinderGord', 'standard'),
(gen_random_uuid(), 'CheckRaiseC', 'aggressive'),
(gen_random_uuid(), 'RoyalFlush88', 'standard'),
(gen_random_uuid(), 'PocketRockets', 'aggressive'),
(gen_random_uuid(), 'FoldToWin', 'passive'),
(gen_random_uuid(), 'StacksOnStacks', 'aggressive'),
(gen_random_uuid(), 'BlindStealer', 'aggressive'),
(gen_random_uuid(), 'TheNit', 'passive'),
(gen_random_uuid(), 'VPIP_God', 'aggressive'),
(gen_random_uuid(), 'LimpingLarry', 'passive'),
(gen_random_uuid(), 'FishDetector', 'standard'),
(gen_random_uuid(), 'NutHunter', 'standard'),
(gen_random_uuid(), 'GTO_Bot', 'standard'),
(gen_random_uuid(), 'RazzleDazzle', 'aggressive'),
(gen_random_uuid(), 'SevenDeuce', 'aggressive'),
(gen_random_uuid(), 'ShowdownSean', 'standard'),
(gen_random_uuid(), 'BadBeatBen', 'standard'),
(gen_random_uuid(), 'QuadsAreReal', 'standard'),
(gen_random_uuid(), 'StraightShot', 'standard'),
(gen_random_uuid(), 'BubbleBoy', 'passive'),
(gen_random_uuid(), 'FinalTableF', 'standard'),
(gen_random_uuid(), 'MainEventMike', 'aggressive'),
(gen_random_uuid(), 'HighStakesHarry', 'aggressive'),
(gen_random_uuid(), 'NoLimitNick', 'aggressive'),
(gen_random_uuid(), 'PotLimitPete', 'standard'),
(gen_random_uuid(), 'SmallBlindS', 'passive'),
(gen_random_uuid(), 'BigBlindB', 'standard'),
(gen_random_uuid(), 'DealerDave', 'standard'),
(gen_random_uuid(), 'TheMechanic', 'standard'),
(gen_random_uuid(), 'CardCounter', 'standard'),
(gen_random_uuid(), 'WizardOfOdds', 'standard'),
(gen_random_uuid(), 'LuckyLou', 'standard'),
(gen_random_uuid(), 'BadMojo', 'aggressive'),
(gen_random_uuid(), 'FullHouseFred', 'standard'),
(gen_random_uuid(), 'TripsAhoy', 'standard'),
(gen_random_uuid(), 'PairOfKings', 'standard'),
(gen_random_uuid(), 'WildCard', 'aggressive'),
(gen_random_uuid(), 'SteadyEddy', 'standard'),
(gen_random_uuid(), 'RockSolid', 'passive'),
(gen_random_uuid(), 'CallingStation', 'passive');
-- Add more as needed... 
